export const GET_TEST_REQUEST = "GET_TEST_REQUEST";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";
export const GET_TEST_FAILURE = "GET_TEST_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

export const GET_PROJECT_CATEGORIES_REQUEST = "GET_PROJECT_CATEGORIES_REQUEST";
export const GET_PROJECT_CATEGORIES_SUCCESS = "GET_PROJECT_CATEGORIES_SUCCESS";
export const GET_PROJECT_CATEGORIES_FAILURE = "GET_PROJECT_CATEGORIES_FAILURE";

export const GET_FEATURED_PROJECTS_REQUEST = "GET_FEATURED_PROJECTS_REQUEST";
export const GET_FEATURED_PROJECTS_SUCCESS = "GET_FEATURED_PROJECTS_SUCCESS";
export const GET_FEATURED_PROJECTS_FAILURE = "GET_FEATURED_PROJECTS_FAILURE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const POST_RESERVATION_REQUEST = "POST_RESERVATION_REQUEST";
export const POST_RESERVATION_SUCCESS = "POST_RESERVATION_SUCCESS";
export const POST_RESERVATION_FAILURE = "POST_RESERVATION_FAILURE";

export const GET_RESERVATION_REQUEST = "GET_RESERVATION_REQUEST";
export const GET_RESERVATION_SUCCESS = "GET_RESERVATION_SUCCESS";
export const GET_RESERVATION_FAILURE = "GET_RESERVATION_FAILURE";

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const REQUEST_RESET_PASSWORD_REQUEST = "REQUEST_RESET_PASSWORD_REQUEST";
export const REQUEST_RESET_PASSWORD_SUCCESS = "REQUEST_RESET_PASSWORD_SUCCESS";
export const REQUEST_RESET_PASSWORD_FAILURE = "REQUEST_RESET_PASSWORD_FAILURE";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

export const GET_RESERVATION_QUOTA_STATUS_REQUEST = "GET_RESERVATION_QUOTA_STATUS_REQUEST";
export const GET_RESERVATION_QUOTA_STATUS_SUCCESS = "GET_RESERVATION_QUOTA_STATUS_SUCCESS";
export const GET_RESERVATION_QUOTA_STATUS_FAILURE = "GET_RESERVATION_QUOTA_STATUS_FAILURE";

export const RESET_SIGNUP = "RESET_SIGNUP";
export const RESET_RESERVATION_REQUEST = "RESET_RESERVATION_REQUEST";
export const RESET_PASSWORD_RESET_STATE = "RESET_PASSWORD_RESET_STATE";
export const RESET_LOGIN_STATE = "RESET_LOGIN_STATE";